export const Users = [
  {
    id:1,
    profilePicture: "person/Odri.jpg",
    username: "Lee Yun Hee",
  },
  {
    id:2,
    profilePicture: "person/Daniel.jpg",
    username: "Daniel Henney",
  },
  {
    id:3,
    profilePicture: "person/Han.jpg",
    username: "Han So hee",
  },
  {
    id:4,
    profilePicture: "person/Jin.jpg",
    username: "Son Ye Jin",
  },
  {
    id:5,
    profilePicture: "person/Son.jpg",
    username: "Son Heung Min",
  },
  {
    id:6,
    profilePicture: "person/Jun.jpg",
    username: "Jeon Ji Hyeon",
  },
  {
    id:7,
    profilePicture: "person/Young.jpg",
    username: "Lee Young Ae",
  },
  {
    id:8,
    profilePicture: "person/Suk.jpg",
    username: "Yoo Jae Suk",
  },
  {
    id:9,
    profilePicture: "person/Song.jpg",
    username: "Song Hye Kyo",
  },
  {
    id:10,
    profilePicture: "person/Ye.jpg",
    username: "Han Ye Seul",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Great view of Lotte Tower.",
    photo: "post/j.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "post/tree.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment!!",
    photo: "post/Red.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "post/Food.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "post/London.png",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "post/dream.png",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "post/flower.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "post/Ja.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "My Dog~:)",
    photo: "post/Dog.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "post/Truffle.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
